name: her_balance
description: Herbalance – preventive health + mental wellness (Kenya)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  shared_preferences: ^2.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: assets/icon.png
  min_sdk_android: 21
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon.png
    background_color: "#FFFFFF"
    theme_color: "#7C4DFF"
  windows:
    generate: true
    image_path: assets/icon.png
  macos:
    generate: true
    image_path: assets/icon.png
